// <auto-generated />
using System;
using Credito.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credito.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoDeCredito))]
    [Migration("20260907032230_ContratacaoELiquidacao")]
    partial class ContratacaoELiquidacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Credito.Dominio.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssinadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PrazoEmMeses")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PrimeiroVencimento")
                        .HasColumnType("date");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sistema")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaMensal")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("ValorFinanciado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Contratos_Proposta");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Contratos.ParcelaContratada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amortizacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChaveDoPagamento")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Juros")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PagaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("SaldoDevedor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_ParcelasContratadas_Contrato_Numero");

                    b.HasIndex("Vencimento", "PagaEm")
                        .HasDatabaseName("IX_ParcelasContratadas_Vencimento_Pagamento");

                    b.ToTable("ParcelasContratadas", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Decisoes.AvaliacaoDeRegra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aprovou")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("DecisaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LimiteExigido")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorObservado")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("DecisaoId", "Ordem")
                        .HasDatabaseName("IX_AvaliacoesDeRegra_Decisao_Ordem");

                    b.ToTable("AvaliacoesDeRegra", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Decisoes.Decisao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aprovada")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AvaliadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreObservado")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaMensalAplicada")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("VersaoDaPolitica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId")
                        .HasDatabaseName("IX_Decisoes_Proposta");

                    b.ToTable("Decisoes", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Politicas.FaixaDeTaxa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PoliticaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreMaximo")
                        .HasColumnType("int");

                    b.Property<int>("ScoreMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaMensal")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("PoliticaId", "ScoreMinimo")
                        .HasDatabaseName("IX_FaixasDeTaxa_Politica_Score");

                    b.ToTable("FaixasDeTaxa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01930000-0000-7000-8000-000000000011"),
                            PoliticaId = new Guid("01930000-0000-7000-8000-000000000001"),
                            ScoreMaximo = 499,
                            ScoreMinimo = 0,
                            TaxaMensal = 0.049m
                        },
                        new
                        {
                            Id = new Guid("01930000-0000-7000-8000-000000000012"),
                            PoliticaId = new Guid("01930000-0000-7000-8000-000000000001"),
                            ScoreMaximo = 699,
                            ScoreMinimo = 500,
                            TaxaMensal = 0.029m
                        },
                        new
                        {
                            Id = new Guid("01930000-0000-7000-8000-000000000013"),
                            PoliticaId = new Guid("01930000-0000-7000-8000-000000000001"),
                            ScoreMaximo = 849,
                            ScoreMinimo = 700,
                            TaxaMensal = 0.019m
                        },
                        new
                        {
                            Id = new Guid("01930000-0000-7000-8000-000000000014"),
                            PoliticaId = new Guid("01930000-0000-7000-8000-000000000001"),
                            ScoreMaximo = 1000,
                            ScoreMinimo = 850,
                            TaxaMensal = 0.012m
                        });
                });

            modelBuilder.Entity("Credito.Dominio.Politicas.PoliticaDeCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ComprometimentoMaximo")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("PrazoMaximoEmMeses")
                        .HasColumnType("int");

                    b.Property<int>("PrazoMinimoEmMeses")
                        .HasColumnType("int");

                    b.Property<int>("ScoreMinimo")
                        .HasColumnType("int");

                    b.Property<int>("ValidadeDaAprovacaoEmDias")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Versao")
                        .IsUnique()
                        .HasDatabaseName("IX_Politicas_Versao");

                    b.ToTable("Politicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01930000-0000-7000-8000-000000000001"),
                            ComprometimentoMaximo = 0.30m,
                            PrazoMaximoEmMeses = 96,
                            PrazoMinimoEmMeses = 6,
                            ScoreMinimo = 500,
                            ValidadeDaAprovacaoEmDias = 30,
                            ValorMaximo = 100000m,
                            ValorMinimo = 1000m,
                            Versao = 1,
                            VigenteDesde = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImpressaoDoPedido")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PrazoEmMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sistema")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Propostas_ChaveIdempotencia");

                    b.ToTable("Propostas", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.TransicaoDeEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("De")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Para")
                        .HasColumnType("int");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("IX_TransicoesDeEstado_Proposta_Sequencia");

                    b.ToTable("TransicoesDeEstado", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Contratos.Contrato", b =>
                {
                    b.HasOne("Credito.Dominio.Propostas.Proposta", null)
                        .WithMany()
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Contratos.ParcelaContratada", b =>
                {
                    b.HasOne("Credito.Dominio.Contratos.Contrato", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Decisoes.AvaliacaoDeRegra", b =>
                {
                    b.HasOne("Credito.Dominio.Decisoes.Decisao", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("DecisaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Decisoes.Decisao", b =>
                {
                    b.HasOne("Credito.Dominio.Propostas.Proposta", null)
                        .WithMany("Decisoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Politicas.FaixaDeTaxa", b =>
                {
                    b.HasOne("Credito.Dominio.Politicas.PoliticaDeCredito", null)
                        .WithMany("Faixas")
                        .HasForeignKey("PoliticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.OwnsOne("Credito.Dominio.Comum.CpfProtegido", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PropostaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cifrado")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CpfCifrado");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CpfHash");

                            b1.HasKey("PropostaId");

                            b1.HasIndex("Hash")
                                .HasDatabaseName("IX_Propostas_CpfHash");

                            b1.ToTable("Propostas");

                            b1.WithOwner()
                                .HasForeignKey("PropostaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.TransicaoDeEstado", b =>
                {
                    b.HasOne("Credito.Dominio.Propostas.Proposta", null)
                        .WithMany("Transicoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Contratos.Contrato", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Credito.Dominio.Decisoes.Decisao", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("Credito.Dominio.Politicas.PoliticaDeCredito", b =>
                {
                    b.Navigation("Faixas");
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.Navigation("Decisoes");

                    b.Navigation("Transicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
