// <auto-generated />
using System;
using Credito.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credito.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoDeCredito))]
    partial class ContextoDeCreditoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImpressaoDoPedido")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PrazoEmMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sistema")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Propostas_ChaveIdempotencia");

                    b.ToTable("Propostas", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.TransicaoDeEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("De")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Para")
                        .HasColumnType("int");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId", "OcorridaEm")
                        .HasDatabaseName("IX_TransicoesDeEstado_Proposta_Ocorrencia");

                    b.ToTable("TransicoesDeEstado", (string)null);
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.OwnsOne("Credito.Dominio.Comum.CpfProtegido", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PropostaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cifrado")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CpfCifrado");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CpfHash");

                            b1.HasKey("PropostaId");

                            b1.HasIndex("Hash")
                                .HasDatabaseName("IX_Propostas_CpfHash");

                            b1.ToTable("Propostas");

                            b1.WithOwner()
                                .HasForeignKey("PropostaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.TransicaoDeEstado", b =>
                {
                    b.HasOne("Credito.Dominio.Propostas.Proposta", null)
                        .WithMany("Transicoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Credito.Dominio.Propostas.Proposta", b =>
                {
                    b.Navigation("Transicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
